/*
 * protocoloComunicacion.h
 *
 *  Created on: 17/9/2017
 *      Author: utnso
 */

#ifndef PROTOCOLOCOMUNICACION_H_
#define PROTOCOLOCOMUNICACION_H_

typedef enum {PORTYAMA = 9000, PORTMASTER, PORTNODO, PORTFILESYSTEM} puertos;

typedef enum {SOLICITUDJOB=1, PEDIDOREDUCCION, FALLOTRANSFORMACION, FALLOREDLOCAL, FALLOREDGLOBAL} ConexionesYAMA;
typedef enum {TRANSFORMACION=1, TRANSFORMACIONOK} ConexionesMaster;
typedef enum {SOLICITUDARCHIVO = 3} ConexionesFileSystem;
typedef enum {TRANSFORMACIONWORKER=1, REDUCLOCAL, REDUCCIONGLOBAL, ALMACENAMIENTO,
	  SOLICITUDARCHIVOWORKER, RECEPCIONARCHIVOWORKER, FILESYSTEMOK, FILESYSTEMERROR,
	  HANDSHAKE} ConexionesWorker;

#endif /* PROTOCOLOCOMUNICACION_H_ */
