/*
 * conexionesWorker.h
 *
 *  Created on: 12/9/2017
 *      Author: utnso
 */

#ifndef CONEXIONESWORKER_H_
#define CONEXIONESWORKER_H_

enum tipoMensaje {TRANSFORMACION=1, REDUCCIONLOCAL, REDUCCIONGLOBAL, ALMACENAMIENTO,
				  SOLICITUDARCHIVOWORKER, RECEPCIONARCHIVOWORKER, FILESYSTEMOK, FILESYSTEMERROR};

#endif /* CONEXIONESWORKER_H_ */
